#include <BrowsePath.h>

struct Browse_type BrowseDat[] = {
	/*Browsepath,Variable/Argument,Argument,NameSpaceIndex,Identifier,Access*/
	{"/0:Objects/0:Server/0:ServerStatus/0:CurrentTime","PowerPanel.Data.Time.CurrentDateTime","",0x0000,"","S"},
	{"/3:Diagnostics/4:CPUCore0Usage","PowerPanel.Data.Diagnostics.CPUCore0Usage","",0x0000,"","R"},
	{"/3:Diagnostics/4:CPUCore1Usage","PowerPanel.Data.Diagnostics.CPUCore1Usage","",0x0000,"","R"},
	{"/3:Diagnostics/4:CPUUsage","PowerPanel.Data.Diagnostics.CPUUsage","",0x0000,"","R"},
	{"/3:Diagnostics/4:MemoryAvailable","PowerPanel.Data.Diagnostics.MemoryAvailable","",0x0000,"","R"},
	{"/3:Diagnostics/4:MemoryTotal","PowerPanel.Data.Diagnostics.MemoryTotal","",0x0000,"","R"},
	{"/3:Status/4:Temperature0","PowerPanel.Data.Status.Temperature0","",0x0000,"","R"},	
	{"/3:Status/4:USBFlashDrive0","PowerPanel.Data.Status.USBFlashDrive0","",0x0000,"","R"},
	{"/3:Status/4:USBFlashDrive1","PowerPanel.Data.Status.USBFlashDrive1","",0x0000,"","R"},
	{"/2:Identification/3:CompatibilityId","PowerPanel.Data.AboutInfo.CompatibilityId","",0x0000,"","R"},
	{"/2:Identification/3:ProductCode","PowerPanel.Data.AboutInfo.ProductCode","",0x0000,"","R"},
	{"/2:Identification/3:VendorId","PowerPanel.Data.AboutInfo.VendorId","",0x0000,"","R"},
	{"/2:Identification/2:DeviceRevision","PowerPanel.Data.AboutInfo.DeviceRevision","",0x0000,"","R"},
	{"/2:Identification/2:HardwareRevision","PowerPanel.Data.AboutInfo.HardwareRevision","",0x0000,"","R"},
	{"/2:Identification/2:Manufacturer","Manufacturer","",0x0000,"","R"},
	{"/2:Identification/2:Model","Model","",0x0000,"","R"},
	{"/2:Identification/2:RevisionCounter","PowerPanel.Data.AboutInfo.RevisionCounter","",0x0000,"","R"},
	{"/2:Identification/2:SerialNumber","PowerPanel.Data.AboutInfo.SerialNumber","",0x0000,"","R"},
	{"/2:Identification/2:SoftwareRevision","PowerPanel.Data.AboutInfo.SoftwareRevision","",0x0000,"","R"},
	{"/3:Configuration/4:Startup/4:StartMode","PowerPanel.Data.Startup.StartMode","",0x0000,"","W"},
	{"/3:Configuration/4:Startup/4:ShowBootLogoVNC","PowerPanel.Data.Startup.ShowBootLogoVNC","",0x0000,"","W"},
	{"/3:Configuration/4:Startup/4:ShowBootLogoWeb","PowerPanel.Data.Startup.ShowBootLogoWeb","",0x0000,"","W"},
	{"/3:Configuration/4:Network/4:Hostname","PowerPanel.Data.Network.Hostname","",0x0000,"","W"},
	{"/3:Configuration/4:Network/4:NetworkMode","PowerPanel.Data.Network.NetworkMode","",0x0000,"","W"},
	{"/3:Configuration/4:Network/4:ActivateDNS","PowerPanel.Data.Network.ActivateDNS","",0x0000,"","W"},
	{"/3:Configuration/4:Network/4:DNSSuffix","PowerPanel.Data.Network.DNSSuffix","",0x0000,"","W"},
	{"/3:Configuration/4:Network/4:GetDNSFromDHCP","PowerPanel.Data.Network.GetDNSFromDHCP","",0x0000,"","W"},
	{"/3:Configuration/4:Network/4:PrimaryDNS","PowerPanel.Data.Network.PrimaryDNS","",0x0000,"","W"},
	{"/3:Configuration/4:Network/4:SecondaryDNS","PowerPanel.Data.Network.SecondaryDNS","",0x0000,"","W"},
	{"/3:Configuration/4:Network/4:TertiaryDNS","PowerPanel.Data.Network.TertiaryDNS","",0x0000,"","W"},
	{"/3:Configuration/4:Network/4:IpAddress","PowerPanel.Data.Network.IpAddress","",0x0000,"","W"},
	{"/3:Configuration/4:Network/4:SubnetMask","PowerPanel.Data.Network.SubnetMask","",0x0000,"","W"},
	{"/3:Configuration/4:Network/4:DefaultGateway","PowerPanel.Data.Network.DefaultGateway","",0x0000,"","W"},
	{"/3:Configuration/4:Time/4:EnableNTPClient","PowerPanel.Data.Time.EnableNTPClient","",0x0000,"","W"},
	{"/3:Configuration/4:Time/4:NTPServer1","PowerPanel.Data.Time.NTPServer1","",0x0000,"","W"},
	{"/3:Configuration/4:Screen/4:DisplayBrightness","PowerPanel.Data.Screen.DisplayBrightness","",0x0000,"","W"},
	{"/3:Configuration/4:Screen/4:ScreenRotation","PowerPanel.Data.Screen.ScreenRotation","",0x0000,"","W"},
	{"/3:Configuration/4:Screen/4:EnableScreensaver","PowerPanel.Data.Screen.EnableScreensaver","",0x0000,"","W"},
	{"/3:Configuration/4:Screen/4:ScreensaverIdleTime","PowerPanel.Data.Screen.ScreensaverIdleTime","",0x0000,"","W"},
	{"/3:Configuration/4:Screen/4:ScreensaverType","PowerPanel.Data.Screen.ScreensaverType","",0x0000,"","W"},
	{"/3:Configuration/4:Screen/4:BootAnimationDelay","PowerPanel.Data.Screen.BootAnimationDelay","",0x0000,"","W"},
	{"/3:Configuration/4:Screen/4:BootAnimationLeftPos","PowerPanel.Data.Screen.BootAnimationLeftPos","",0x0000,"","W"},
	{"/3:Configuration/4:Screen/4:BootAnimationTopPos","PowerPanel.Data.Screen.BootAnimationTopPos","",0x0000,"","W"},
	{"/3:Configuration/4:Audio/4:EnableBuzzer","PowerPanel.Data.Audio.EnableBuzzer","",0x0000,"","W"},
	{"/3:Configuration/4:Audio/4:BuzzerSource","PowerPanel.Data.Audio.BuzzerSource","",0x0000,"","W"},
	{"/3:Configuration/4:Audio/4:BuzzerFrequency","PowerPanel.Data.Audio.BuzzerFrequency","",0x0000,"","W"},
	{"/3:Configuration/4:Audio/4:BuzzerDuration","PowerPanel.Data.Audio.BuzzerDuration","",0x0000,"","W"},
	{"/3:Configuration/4:Gesture/4:OpenServicePage","PowerPanel.Data.Gesture.OpenServicePage","",0x0000,"","W"},
	{"/3:Configuration/4:Vnc/4:VNCServer","PowerPanel.Data.Vnc.VNCServer","",0x0000,"","W"},
	{"/3:Configuration/4:Vnc/4:UseRfbExtension","PowerPanel.Data.Vnc.UseRfbExtension","",0x0000,"","W"},
	{"/3:Configuration/4:Vnc/4:VNCLocalWindowScaling","PowerPanel.Data.Vnc.VNCLocalWindowScaling","",0x0000,"","W"},
	{"/3:Configuration/4:Vnc/4:VNCBackgroundColor","PowerPanel.Data.Vnc.VNCBackgroundColor","",0x0000,"","W"},
	{"/3:Configuration/4:Web/4:WebServer","PowerPanel.Data.Web.WebServer","",0x0000,"","W"},
	{"/3:Configuration/4:Web/4:VirtualKeyboardWeb","PowerPanel.Data.Web.VirtualKeyboardWeb","",0x0000,"","W"},
	{"/3:Configuration/4:Web/4:SetOverrideViewport","PowerPanel.Data.Web.SetOverrideViewport","",0x0000,"","W"},
	{"/3:Configuration/4:Web/4:ViewportSettings","PowerPanel.Data.Web.ViewportSettings","",0x0000,"","W"},
	{"/3:Configuration/4:Web/4:DisablePinchGesture","PowerPanel.Data.Web.DisablePinchGesture","",0x0000,"","W"},
	{"/3:Configuration/4:Web/4:IgnoreServerCertificateErrors","PowerPanel.Data.Web.IgnoreServerCertificateErrors","",0x0000,"","W"},
	{"/3:Configuration/4:Web/4:EnableScreenCapture","PowerPanel.Data.Web.EnableScreenCapture","",0x0000,"","W"},
	{"/3:Configuration/4:Web/4:SuppressScrnCaptSecWarn","PowerPanel.Data.Web.SuppressScrnCaptSecWarn","",0x0000,"","W"},
	{"/3:Configuration/4:Storage/4:USBMemoryShare","PowerPanel.Data.Storage.USBMemoryShare","",0x0000,"","W"},
	{"/3:Configuration/4:Storage/4:UserMemoryShare","PowerPanel.Data.Storage.UserMemoryShare","",0x0000,"","W"},
	{"/3:Configuration/4:RemoteAccess/4:EnableRemoteAccess","PowerPanel.Data.RemoteAccess.EnableRemoteAccess","",0x0000,"","W"},
	{"/3:Configuration/4:RemoteAccess/4:RemoteAccessBackEnd","PowerPanel.Data.RemoteAccess.RemoteAccessBackEnd","",0x0000,"","W"},
	{"/3:Configuration/4:RemoteAccess/4:RemoteAccessModeWebGL","PowerPanel.Data.RemoteAccess.RemoteAccessModeWebGL","",0x0000,"","W"},			// Requires firmware 1.6.0 or higher
	{"/3:Configuration/4:RemoteAccess/4:RemoteAccessModeVNC","PowerPanel.Data.RemoteAccess.RemoteAccessModeVNC","",0x0000,"","W"},				// Requires firmware 1.6.0 or higher
	{"/3:Configuration/4:RemoteAccess/4:RemoteAccessPortWebGL","PowerPanel.Data.RemoteAccess.RemoteAccessPortWebGL","",0x0000,"","W"},			// Requires firmware 1.6.0 or higher
	{"/3:Configuration/4:RemoteAccess/4:RemoteAccessWSPortWebGL","PowerPanel.Data.RemoteAccess.RemoteAccessWSPortWebGL","",0x0000,"","W"},		// Requires firmware 1.6.0 or higher
	{"/3:Configuration/4:RemoteAccess/4:RemoteAccessPortVNC","PowerPanel.Data.RemoteAccess.RemoteAccessPortVNC","",0x0000,"","W"},				// Requires firmware 1.6.0 or higher
	{"/2:MethodSet","","",0x0000,"","M"},
	{"/2:MethodSet/4:StartRemoteAccess","","",0x0000,"","M"},
	{"/2:MethodSet/4:StopRemoteAccess","","",0x0000,"","M"},
	{"/2:MethodSet/4:SaveConfiguration","","",0x0000,"","M"},
	{"/2:MethodSet/4:LoadConfiguration","","",0x0000,"","M"},
	{"/2:MethodSet/4:AwakePanel","","",0x0000,"","M"},
	{"/2:MethodSet/4:RestartSystem","","",0x0000,"","M"},																							// Requires firmware 1..0 or higher
	{"/2:MethodSet/4:StartUpdate","","",0x0000,"","M"},
	{"/2:MethodSet/4:BuzzerDefault","","",0x0000,"","M"},
	{"/2:MethodSet/4:SetBrightness","PowerPanel.Method.Brightness","",0x0000,"","M"},
	{"/2:MethodSet/4:SetBrightnessUnlimited","PowerPanel.Method.Brightness","",0x0000,"","M"},
	{"/2:MethodSet/4:SetTime","PowerPanel.Method.ActualTime","",0x0000,"","M"},
	{"/2:MethodSet/4:BuzzerWithPara","PowerPanel.Method.BuzzerFrequency","PowerPanel.Method.BuzzerDuration",0x0000,"","M"},
};
